//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJUMSCBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NJUMSCBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;readMoreUrl&quot;: &quot;&quot; 
        ///  }
        ///].
        /// </summary>
        internal static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;readMoreUrl&quot;: &quot;&quot;
        ///  }
        ///].
        /// </summary>
        internal static string ClubActivity {
            get {
                return ResourceManager.GetString("ClubActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;readMoreUrl&quot;: &quot;&quot;
        ///  }
        ///].
        /// </summary>
        internal static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;技术部&quot;,
        ///    &quot;description&quot;: &quot;技术部是微软俱乐部的一个重要部门，主要负责和技术有关的活动，比如举办学术讲座，做宣传海报等&quot;,
        ///    &quot;readMoreUrl&quot;: &quot;&quot;,
        ///    &quot;president&quot;: &quot;软院 王宁一&quot;,
        ///    &quot;vicePresident&quot;: &quot;软院 陈俊达，物院 王臻郅&quot;
        ///  }
        ///].
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;updatedTime&quot;: &quot;2017-8-11&quot;,
        ///  &quot;github&quot;: &quot;https://github.com/njumsc/NJUMSCBot&quot;
        ///}.
        /// </summary>
        internal static string Metainfo {
            get {
                return ResourceManager.GetString("Metainfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;welcome&quot;: &quot;你好！我是南京大学微软学生俱乐部的机器人，你可以用自然语言询问我任何问题！&quot;,
        ///  &quot;unknownIntent&quot;: &quot;啊抱歉没听懂你在说什么……&quot;,
        ///  &quot;help&quot;: &quot;目前，你可以用自然语言问我关于俱乐部的招新、比赛、活动、部门等信息，以后我们的还会继续增加功能！&quot;,
        ///  &quot;metainfo&quot;: &quot;元数据&quot;
        ///}.
        /// </summary>
        internal static string StringConstants {
            get {
                return ResourceManager.GetString("StringConstants", resourceCulture);
            }
        }
    }
}
