//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJUMSCBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NJUMSCBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;introduction&quot;: &quot;俱乐部会对组员提供很多福利，例如“明日之星”实习生计划，微软“校园菁英计划”以及微软学生夏令营。&quot;,
        ///  &quot;notExist&quot;: &quot;我们好像没有这个福利……&quot;,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;names&quot;: [ &quot;“明日之星”实习生计划&quot;, &quot;明日之星&quot; ],
        ///      &quot;description&quot;: &quot;微软亚洲研究院应该是所有计算机人才梦寐以求的实习/工作机会，微软学生俱乐部的优秀部员将可以通过俱乐部绿色通道，略去简历筛选过程，你的简历可以直接到达导师手中。&quot;,
        ///      &quot;readMoreUrl&quot;: &quot;http://www.msra.cn/zh-cn/connections/academic-programs/tomorrowstars&quot;
        ///    },
        ///    {
        ///      &quot;names&quot;: [ &quot;微软“校园菁英计划”&quot;, &quot;校园菁英计划&quot;, &quot;校园菁英&quot; ],
        ///      &quot;description&quot;: &quot;微软校园菁英计划是针对有好的想法却缺少工具，指导和资金的大学生团队。校园菁英计划的目的不同于比赛，菁英计划希望能 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BenefitInfo {
            get {
                return ResourceManager.GetString("BenefitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;introduction&quot;: &quot;我们每年会举办很多活动，例如技术沙龙，微软校园行等。&quot;,
        ///  &quot;notExist&quot;: &quot;我们貌似没有这个活动……&quot;,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;names&quot;: [ &quot;技术沙龙&quot;, &quot;技术讲座&quot; ],
        ///      &quot;description&quot;: &quot;南京大学微软俱乐部会定期举办技术沙龙，我们将邀请高年级有声望的学长学姐与大家分享一些大家感兴趣的技术问题，并以讲座+互动的形式举行。去年举办过的部分讲座有：机器学习基础，Microsoft Cognitive Service，如何科学上网（翻墙）等。&quot;
        ///    },
        ///    {
        ///      &quot;names&quot;: [ &quot;MR体验活动&quot;, &quot;MR&quot; ],
        ///      &quot;description&quot;: &quot;2018年，南大微俱购入了MR设备并开放给俱乐部内部成员体验，在5月20日校庆日晚开放给全校同学体验，收到了很好的效果。据评价，这是一款“一度曾经让某些俱乐部成员沉迷与空气搏斗无法自拔甚至扬言与抢夺者以死相搏的科（you）技（xi）设备，亲测令人不能自拔，无法fu吸。”&quot;
        ///    },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClubActivityInfo {
            get {
                return ResourceManager.GetString("ClubActivityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;introduction&quot;: &quot;微软学生俱乐部（Microsoft Student Club）是微软亚洲研究院(Microsoft Research Asia, MSRA)下属的学生俱乐部，由MSRA直接提供资金和运营支持。在全国，包括清华，北大，港科大，南大在内的34所一流高校都有各自的微软俱乐部。微软学生俱乐部的创立，是微软亚洲研究院与高校合作培养人才的一种探索。自 2000 年 10 月 15 日第一个俱乐部在四川大学成立起，至今全国已有34所高校拥有了自己的 MSC。俱乐部本着“学习先进技术，开拓创新思维，体验多元文化，成就一流人才”的宗旨，在各高校校团委、相关学院的指导下，通过学生项目、线上微课、产品体验、技术沙龙、学生大赛等活动，培养部员的创新头脑、实践能力和组织能力，让来自不同领域的同学得以展现才华，共同成长。&quot;,
        ///  &quot;\&quot;,&quot;: null,
        ///  &quot;website&quot;: &quot;http://studentclub.msra.cn/&quot;,
        ///  &quot;groupImage&quot;: &quot;https://wx2.sinaimg.cn/mw690/9e4c3c1bgy1fuai8j4oktj20f00k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClubIntroduction {
            get {
                return ResourceManager.GetString("ClubIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;introduction&quot;: &quot;大家可以参加俱乐部以及MSRA举办的各种活动来认识大佬一起学习，每年我们都有微软创新杯（Imagine Cup），微软hackathon，编程之美挑战赛。&quot;,
        ///  &quot;notExist&quot;: &quot;我们貌似没有这个比赛……&quot;,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;names&quot;: [ &quot;微软校园hackathon&quot;, &quot;黑客马拉松&quot;, &quot;黑客松&quot;, &quot;微软hackathon&quot;, &quot;hackathon&quot; ],
        ///      &quot;description&quot;: &quot;Hackathon，中文名黑客松，昵称黑马，小名松松(黑人问号？)，是一群程序猿聚众coding，以合作形式形成某个项目的活动。在Hackathon启动前会限定主题和大方向，各个团队根据这个大方向以团队形式合作coding，在限时内形成自己的项目，最后进行展示与评比。它的灵魂是合作地编写程序和应用。时长一般在几天到一周不等。\n\n在南京，由南京大学、东南大学、南京理工大学、南京航空航天大学微软学生俱乐部共同举办的南京四校hackathon到2017年12月已经举办了三届，人数和影响力逐年增加，2017 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompetitionInfo {
            get {
                return ResourceManager.GetString("CompetitionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;introduction&quot;: &quot;我们目前由三个部门组成，组织部，宣传部和技术部。&quot;,
        ///  &quot;notExist&quot;: &quot;我们好像没有这个部门……我们有组织部，宣传部和技术部。&quot;,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;names&quot;: [ &quot;技术部&quot; ],
        ///      &quot;description&quot;: &quot;技术部主要负责和技术有关的活动，比如举办技术讲座，组织技术活动等。这也是平时主要为大家提供福利的部门。刚过去的一年里，技术部的多位dalao就“科学上网”（doge）和机器学习进行过讲座，干货满满哟~&quot;,
        ///      &quot;president&quot;: &quot;计科 谢乃容&quot;,
        ///      &quot;vicePresident&quot;: &quot;计科 吴秉乐&quot;
        ///    },
        ///    {
        ///      &quot;names&quot;: [ &quot;活动部&quot; ],
        ///      &quot;description&quot;: &quot;活动部主要负责策划和承办各式各样的活动，比如策划新部员的破冰活动等。&quot;,
        ///      &quot;president&quot;: &quot;软院 徐璜林&quot;,
        ///      &quot;vicePresident&quot;: &quot;计科 王月涵&quot;
        ///    },
        ///    {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DepartmentInfo {
            get {
                return ResourceManager.GetString("DepartmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;updatedTime&quot;: &quot;2018-8-15&quot;,
        ///  &quot;github&quot;: &quot;https://github.com/njumsc/NJUMSCBot&quot;
        ///}.
        /// </summary>
        internal static string Metainfo {
            get {
                return ResourceManager.GetString("Metainfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;welcome&quot;: &quot;你好！我是南京大学微软学生俱乐部的机器人，你可以用自然语言询问我任何问题！&quot;,
        ///  &quot;unknownIntent&quot;: &quot;啊抱歉没听懂你在说什么……&quot;,
        ///  &quot;operations&quot;: {
        ///    &quot;俱乐部信息&quot;: &quot;介绍下俱乐部&quot;,
        ///    &quot;活动&quot;: &quot;俱乐部有什么活动&quot;,
        ///    &quot;比赛&quot;: &quot;你们有什么比赛&quot;,
        ///    &quot;部门&quot;: &quot;俱乐部有哪些部门&quot;,
        ///    &quot;福利&quot;: &quot;俱乐部有哪些福利&quot;,
        ///    &quot;招新！&quot;: &quot;怎样加入你们&quot;,
        ///    &quot;帮助&quot;: &quot;帮助&quot;
        ///  },
        ///  &quot;help&quot;: &quot;目前，你可以用自然语言问我关于俱乐部的招新、比赛、活动、部门等信息，以后我们的还会继续增加功能！&quot;,
        ///  &quot;metainfo&quot;: &quot;元数据&quot;,
        ///  &quot;joining&quot;: &quot;欢迎加入QQ群527635833。具体迎新步骤我们将随时更新，欢迎持续关注！&quot;
        ///}.
        /// </summary>
        internal static string StringConstants {
            get {
                return ResourceManager.GetString("StringConstants", resourceCulture);
            }
        }
    }
}
